version: "3.8"

services:
    web:
        image: python:3.8.3
        build: .
        command: python3.8 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=adminusergidek
            - POSTGRES_PASSWORD=supersecureadminuserpassword
            - POSTGRES_DB=gidek
    
volumes:
    postgres_data:
